units:
  kx: cx
  ky: cy
  px: 2
  py: 2
  ring_rotate: -10
    # Defaults to M2 Screws
  screwSize: 1.5
  standoffSize: 2.5
points:
  zones:
    matrix:
      columns:
        pinky:
          key:
            origin: [ 0, -1cy ]
            rows:
              bottom:
                column_net: P21
              home:
                column_net: P20
              top:
                column_net: P19
        ring:
          key:
            rotate: 0
            stagger: 12.23
            spread: cx
          rows:
            bottom:
              column_net: P18
            home:
              column_net: P15
            top:
              column_net: P14
        middle:
          key:
            origin: [ 0, -1cy ]
            rotate: 0
            stagger: 4.46
            spread: cx
          rows:
            bottom:
              column_net: P16
            home:
              column_net: P10
            top:
              column_net: P9
        index:
          key:
            origin: [ 0, -1cy ]
            rotate: 0
            stagger: -4.86
            spread: cx
          rows:
            bottom:
              column_net: P8
            home:
              column_net: P7
            top:
              column_net: P6
        inner:
          key:
            origin: [ 0, -1cy ]
            rotate: 0
            spread: cx
            stagger: -1.88
          rows:
            bottom:
              column_net: P5
            home:
              column_net: P4
            top:
              column_net: P3
      rows:
        bottom:
          padding: 1ky
        home:
          padding: 1ky
        top:
          padding: 1ky
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [ 7.5, -25.06 ]
      columns:
        right:
          key:
            origin: [-cx/2, -cy/2]
            stagger: 5.64
            spread: -3.04
            splay: -30
            column_net: P2
            column_mark: R
        middle:
          key:
            origin: [-cx/2, -cy/2]
            splay: 15
            stagger: -4.72
            spread: -cx + 0.27
            column_net: P0
            column_mark: M
        left:
          key:
            origin: [-cx/2, -cy/2]
            stagger: -4.4
            spread: -cx + 0.6
            splay: 14
            column_net: P1
            column_mark: P
      rows:
        thumb:
          padding: 0
outlines:
  # board dimensions according to JLCPCB: 122.28 mm x 101.05 mm
    raw:
      - what: rectangle
        size: [kx, ky]
        corner: px
        where: true
    top_arc_left_intersect:
      - what: polygon
        points:
          - ref: matrix_pinky_top
            shift: [-cx/2, cy/2]
          - ref: matrix_middle_top
            shift: [cx/2, cy/2]
          - ref: matrix_middle_top
            shift: [cx/2, 2cy]
          - ref: matrix_pinky_top
            shift: [-cx/2, 3cy]
    top_arc_right_intersect:
      - what: polygon
        points:
          - ref: matrix_middle_top
            shift: [cx/2, -cy/2]
          - ref: matrix_middle_top
            shift: [cx/2, 2cy]
          - ref: matrix_inner_top
            shift: [cx/2, 3cy]
          - ref: matrix_inner_top
            shift: [cx/2, cy/2]
    bottom_arc_left_intersect:
      - what: polygon
        points:
          - ref: matrix_pinky_bottom
            shift: [-cx/2, cy/2]
          - ref: matrix_middle_bottom
            shift: [cx/2, cy/2]
          - ref: matrix_middle_bottom
            shift: [cx/2, -4cy]
          - ref: matrix_pinky_bottom
            shift: [-cx/2, -3cy]
    bottom_arc_right_intersect:
      - what: polygon
        points:
          - ref: matrix_middle_bottom
            shift: [cx/2, -cy/2]
          - ref: thumbfan_right_thumb
            shift: [cx/2, cy/2]
          - ref: thumbfan_right_thumb
            shift: [cx, -cy/2]
          - ref: thumbfan_right_thumb
            shift: [-2.1cx, -4cy]
    right_cut:
      - what: polygon
        points:
          - ref: thumbfan_right_thumb
            shift: [cx/2, -cy/2]
          - ref: thumbfan_right_thumb
            shift: [cx/2, 5cy]
          - ref: thumbfan_right_thumb
            shift: [3cx, 5cy]
          - ref: thumbfan_right_thumb
            shift: [3cx, -cy/2]

    arc_top_left: #todo check with top left corner shift
      - what: circle
        adjust:
          ref: matrix_middle_bottom
          shift: [2.2, -24.22]
        radius: 68.7
      - what: outline
        name: top_arc_left_intersect
        operation: intersect

    arc_top_right:
      - what: circle
        adjust:
          ref: matrix_middle_bottom
          shift: [-5.58, -99.1]
        radius: 144.02
      - what: outline
        name: top_arc_right_intersect
        operation: intersect
    arc_bottom_left:
      - what: circle
        adjust:
          ref: matrix_middle_bottom
          shift: [-42.42, -395.95]
        radius: 368.6
      - what: outline
        name: bottom_arc_left_intersect
        operation: intersect
    arc_bottom_right:
      - what: circle
        adjust:
          ref: matrix_middle_bottom
          shift: [-13.3, -175.24]
        radius: 145.98
      - what: outline
        name: bottom_arc_right_intersect
        operation: intersect
    arc_bottom:
      - what: outline
        name: arc_bottom_left
      - what: outline
        name: arc_bottom_right

    edge_points:
      - what: polygon
        points:
          - ref: matrix_pinky_top
            shift: [-cx/2, cy/2]
          - ref: matrix_ring_top
            shift: [-cx/2, cy/2]
          - ref: matrix_middle_top
            shift: [-cx/2, cy/2]
          - ref: matrix_middle_top
            shift: [cx/2, cy/2]
          - ref: matrix_index_top
            shift: [cx/2, cy/2]
          - ref: matrix_inner_top
            shift: [cx/2, cy/2]
          - ref: matrix_inner_bottom
            shift: [cx/2, -cy/2]
          - ref: thumbfan_right_thumb
            shift: [cx/2, cy/2]
          - ref: thumbfan_right_thumb
            shift: [cx/2, -15]
          - ref: matrix_pinky_bottom
            shift: [-cx/2, -1.5cy]
          - ref: matrix_pinky_top
            shift: [-cx/2, cy/2]
    controller_area:
      main:
        what: rectangle
        adjust:
          ref:
            - matrix_inner_top
          shift: [16, -29]
        size: [32, 62.5]
        corner: px
    keycaps:
      main:
        what: rectangle
        where: true
        size: [kx, ky]
        bound: false
        corner: 1
    mounting:
      - what: circle
        radius: screwSize
        where:
          ref: [matrix_pinky_top]
          shift: [0.37kx, 0.65ky]

      - what: circle
        radius: screwSize
        where:
          ref: [matrix_inner_top]
          shift: [0.48kx, -0.5ky]

      - what: circle
        radius: screwSize
        where:
          ref: [matrix_pinky_bottom]
          shift: [0.7kx, -0.2ky]

      - what: circle
        radius: screwSize
        where:
          ref: [thumbfan_right_thumb]
          shift: [0, 0.8ky]
    standoff:
      - what: circle
        radius: standoffSize
        where:
          ref: [matrix_pinky_top]
          shift: [0.37kx, 0.65ky]

      - what: circle
        radius: standoffSize
        where:
          ref: [matrix_inner_top]
          shift: [0.48kx, -0.5ky]

      - what: circle
        radius: standoffSize
        where:
          ref: [matrix_pinky_bottom]
          shift: [0.7kx, -0.2ky]

      - what: circle
        radius: standoffSize
        where:
          ref: [thumbfan_right_thumb]
          shift: [0, 0.8ky]

    base_outline:
      main:
        what: outline
        name: raw
      arc_top_left:
        what: outline
        name: arc_top_left
      arc_top_right:
        what: outline
        name: arc_top_right
      edge:
        what: outline
        name: edge_points
      controller:
        what: outline
        name: controller_area
      arc_bottom_right:
        what: outline
        name: arc_bottom
        operation: subtract
      right_cut:
        what: outline
        name: right_cut
        operation: subtract

    plate:
      main:
        what: outline
        name: base_outline
      switches:
        what: outline
        name: keycaps
        operation: subtract
    pcb:
      main:
        what: outline
        name: base_outline
pcbs:
  board:
    outlines:
      edge:
        outline: pcb
        layer: Edge.Cuts
    footprints:
      choc:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: GND
      mcu_l:
        what: promicro
        params:
          orientation: up
        adjust:
          ref:
            - matrix_inner_top
          shift: [20, -15.8]
          rotate: 270
      mcu_r:
        what: promicro
        params:
          orientation: down
        adjust:
          ref:
            - matrix_inner_top
          shift: [22.5, -17.05]
          rotate: 270
      reset:
        what: reset_button
        adjust:
          ref:
            - matrix_inner_bottom
          shift: [21.2, -5.9]
          rotate: 180
        params:
          from: GND
          to: RST
      info_l:
        what: text
        adjust:
          shift: [87.376, 9.11]
          rotate: -5
        params:
          text: "Dupa Sweep\\nby KostkaBrukowa"
          justify: left
      info_r:
        what: text
        adjust:
          shift: [87.376, 9.11]
          rotate: -5
        params:
          layer: B.SilkS
          text: "Dupa Sweep\\nby KostkaBrukowa"
          justify: right mirror
      hole_top_left:
        what: mountinghole
        where:
          ref: [matrix_pinky_top]
          shift: [0.37kx, 0.65ky]

      hole_top_right:
        what: mountinghole
        where:
          ref: [matrix_inner_top]
          shift: [0.48kx, -0.5ky]

      hole_bottom_left:
        what: mountinghole
        where:
          ref: [matrix_pinky_bottom]
          shift: [0.7kx, -0.2ky]

      hole_bottom_right:
        what: mountinghole
        where:
          ref: [thumbfan_right_thumb]
          shift: [0, 0.8ky]

cases:
  bottom:
    - name: base_outline
      extrude: 1
  _holes:
    - name: mounting
      extrude: 4
  _standoffs:
    - name: standoff
      extrude: 4
  case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: bottom
      operation: add
