module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    broom: require('./broom'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mountinghole: require('./mountinghole'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro_flippable'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    text: require('./text'),
    trrs: require('./trrs'),
    via: require('./via'),
    reset_button: require('./reset_button'),
}
