file_format: "1"
id: dupa_sweep
name: DupaSweep
type: shield
url: https://boardsource.xyz/store/5f2e7e4a2902de7151494f92
requires: [pro_micro]
features:
  - keys
siblings:
  - dupa_sweep_left
  - dupa_sweep_right
