on: [push, pull_request, workflow_dispatch]

name: Build
jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - name: Install dependencies
        run: |
          cp -r ergogen/* ./
          npm install
      - name: Generate unrouted PCBs
        run: |
          cp ./promicro.js ./node_modules/ergogen/src/footprints
          cp ./button.js ./node_modules/ergogen/src/footprints
          cp ./broom.js ./node_modules/ergogen/src/footprints
          cp ./index.js ./node_modules/ergogen/src/footprints
          cp ./text.js ./node_modules/ergogen/src/footprints
          cp ./footprints/promicro_flippable.js ./node_modules/ergogen/src/footprints
          cp ./footprints/reset_button.js ./node_modules/ergogen/src/footprints
          npm run gen
      - name: Export DSN for main PCB
        uses: ./.github/actions/export-dsn
        with:
          pcb_file: output/pcbs/board.kicad_pcb
          dsn_file: /github/workspace/output/pcbs/board.dsn
      - name: Autoroute main PCB
        uses: ./.github/actions/autoroute
        with:
          dsn_file: /github/workspace/output/pcbs/board.dsn
          ses_file: output/pcbs/board.ses
      - name: Import SES into main PCB
        uses: ./.github/actions/import-ses
        with:
          pcb_input_file: output/pcbs/board.kicad_pcb
          pcb_output_file: output/pcbs/board_routed.kicad_pcb
          ses_file: output/pcbs/board.ses
      - name: Export Gerbers for main PCB
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: output/pcbs/board.kicad_pcb
          gerbers_dir: output/gerbers/board
      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: samoklava-routed-pcbs-and-gerbers
          path: output
